version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: drom_db
      MYSQL_USER: drom_user
      MYSQL_PASSWORD: drom_password
    ports:
      - 3306:3306
  web:
    image: php:7.2-apache
    build: ./php
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
      - ./apache2:/etc/apache2/sites-available/
    ports:
      - 80:80


  node:
    image: node:latest
    environment: 
      NODE_ENV: development
    working_dir: /home/www/public
    volumes:
      - ./www/public:/home/www/public
    command: npm install
