version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: drom_db
      MYSQL_USER: drom_user
      MYSQL_PASSWORD: drom_password
    ports:
      - 3306:3306
  web:
    image: php:7.2-apache
    build: ./php
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html/:z
      - ./apache2:/etc/apache2/sites-available/
  node:
    image: node:latest
    environment: 
      NODE_ENV: development
    working_dir: /var/www/html/public
    volumes:
      - ./www/public:/var/www/html/public
    command: npm install
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html/
    command: composer install