version: '3'

services:
  web:
    image: php:7.2-apache
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: drom_db
      MYSQL_USER: drop_user
      MYSQL_PASSWORD: drop_password
  node:
    image: node:latest
    environment: 
      NODE_ENV: development
    working_dir: /home/app
    volumes:
      - ./www:/home/app
    command: npm install
